# Generated by Django 5.0.7 on 2024-07-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockList',
        ),
    ]
